### ISSUE TITLE
This can be bypassed in multiple ways

### ISSUE THREAD

**Issue by 6ce** [Exunys/Anti-Kick#2]
I know exploiting is mostly dead, but there are methods to bypassing/detecting your "anti-kick"

Method 1:
```lua
local plr = game.Players.LocalPlayer

plr["Kick\0"](plr) -- namecallmethod is not the same as "kick" or "Kick", therefore will bypass ur method
```
Method 2:
```lua
local success, err = pcall(function()
    workspace:Kick() -- will not error when it normally should because you always hook "kick" and dont check the self object
end)

if not err or success then
    -- detected ur anti kick and can do w/e they like such as crashing the client or kicking w/ a remoteevent
end
```

**Comment by Exunys** [comment]
Hello, thanks for your reply. The first method you shared wouldn't even work, it would throw an error of the nature "attempted to call nil" because of the "\0" (its a null character). I am not aware of the past Roblox Studio updates so I apologize if I am wrong. This however can be fixed immediately with a few regex patterns.

And yes you are correct, this code is pretty old and made in like 2 minutes because I was bypassing some client sided anti-cheat a long time ago while I was learning. I do not share my modern security methods and techniques publicly and for free however. To fix this you can just add another "and" condition in the if statement.

```lua
and ({...})[1] == Players.LocalPlayer and --...
```

I think I had a self check in an older version if I recall but I have no clue why I removed it, maybe I just forgot it. You can see the "Players" variable isn't even used in the code.

I will (if I remember) fix and upgrade this code whenever and if a new trusted exploit ever releases, however feel free to do a pull request, you'll get credited. Thank you for the acknowledgement I totally forgot about this repository!
